config/routes.rb
Rails.application.routes.draw do
  resources :movies
  devise_for :views
  devise_for :users do 
    root :to => "devise/sessions#new"
  end
  root to: "movies#index"

  get '/public', to: 'movies#public'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/movie.rb
class Movie < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/view.rb
class View < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authenticate_user!
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_movie, only: [:show, :edit, :update, :destroy]

  def index
    @movies = Movie.where(user_id: current_user.id, public: false)
  end

  def public 
    @movies = Movie.where(public: true)
  end  

  def show
  end

  def new
    @movie = Movie.new
  end

  def edit
  end

  def create
    @movie = Movie.new(movie_params)
    @movie.user_id = current_user.id
    respond_to do |format|
      if @movie.save
        format.html { redirect_to @movie, notice: 'Movie was successfully created.' }
        format.json { render :index }
      else
        format.html { render :new }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @movie.update(movie_params)
        format.html { redirect_to @movie, notice: 'Movie was successfully updated.' }
        format.json { render :index }
      else
        format.html { render :edit }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @movie.destroy
    respond_to do |format|
      format.html { redirect_to movies_url, notice: 'Movie was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_movie
      @movie = Movie.find(params[:id])
    end

    def movie_params
      params.require(:movie).permit(:name, :url, :user_id, :public)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Showmovies</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://unpkg.com/video.js/dist/video-js.css" rel="stylesheet">
    <script src="https://unpkg.com/video.js/dist/video.js"></script>
    <script src="https://unpkg.com/videojs-contrib-hls/dist/videojs-contrib-hls.js"></script>
  </head>


  <body class="container">
    <% if user_signed_in? %>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand" href="https://github.com/matiasarenhard/showmovies"><%= fa_icon "github" %></a>
        
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <%= link_to "My Movies", movies_path, class: 'nav-link' %>
            </li>
            <li class="nav-item">
              <%= link_to "Public Movies", public_path, class: 'nav-link' %>
            </li>
          </ul>
          <div class="form-inline my-2 my-lg-0">
          <p style="color: white;">
              <%= current_user.email %>
           </p> 
            <%= link_to('Logout', destroy_user_session_path, method: :delete, class: 'btn btn-outline-danger my-2 my-sm-0') %>   
          </div>
        </div>
      </nav>
    <% end %>  
    <%= yield %>
  </body>
</html>

app/views/movies/_form.html.erb
<%= form_with(model: movie, local: true) do |form| %>
  <% if movie.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(movie.errors.count, "error") %> prohibited this movie from being saved:</h2>

      <ul>
      <% movie.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :url %>
    <%= form.text_field :url %>
  </div>

  <div class="field">
    <%= form.label :public %>
    <%= form.check_box :public %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/movies/edit.html.erb
<h1>Editing Movie</h1>

<%= render 'form', movie: @movie %>

<%= link_to 'Show', @movie %> |
<%= link_to 'Back', movies_path %>

app/views/movies/index.html.erb
<p id="notice"><%= notice %></p>
<h1 class="text-center"> My Movies</h1>
<%= link_to 'New Movie', new_movie_path, class: 'btn btn-success text-center' %>
<br/>
<br/>
<table id="myMovies">
   <thead>
      <tr>
         <th class="hidethis">Id</th>
         <th>Movie</th>
         <th>Options</th>
      </tr>
   </thead>
   <tbody>
      <% @movies.each do |movie| %>
      <tr>
         <td class="hidethis"> <%= movie.name + movie.id.to_s %>
         <td>
         <td>
            <%= movie.name %><br>
            <video id="video-<%=movie.id.to_s %>" width=960 height=540 class="video-js vjs-default-skin" controls>
               <source src= "<%= movie.url %>" type="application/x-mpegURL">
            </video>
            <hr style="border-top-width: 5px; background-color: black;">
         </td>
         <td>
            <%= link_to "edit", movie_path(movie), class: 'btn btn-warning' %>
         </td>
      </tr>
      <% end %>
   </tbody>
</table>
<br>
<script>
   $(document).ready(function() {
      $(".video-js").each(function(){
        var movie_id = $(this)[0].id
        var concat = "#"+movie_id.toString()
        videojs(concat);
      }); 
      $('.hidethis').hide();
   });
   
   
</script>

app/views/movies/new.html.erb
<h1>New Movie</h1>

<%= render 'form', movie: @movie %>

<%= link_to 'Back', movies_path %>

app/views/movies/public.html.erb
<p id="notice"><%= notice %></p>
<h1 class="text-center">Public Movies</h1>
<%= link_to 'New Movie', new_movie_path, class: 'btn btn-success text-center' %>
<br/>
<br/>
<table>
   <thead>
      <tr>
         <th class="hidethis">Id</th>
         <th>User</th>
      </tr>
   </thead>
   <tbody>
      <% @movies.each do |movie| %>
      <tr>
         <td class="hidethis"> <%= movie.name + movie.id.to_s %>
         <td>
         <td>
            <%= movie.name %><br>
            <video id="video-<%=movie.id.to_s %>" width=960 height=540 class="video-js vjs-default-skin" controls>
               <source src= "<%= movie.url %>" type="application/x-mpegURL">
            </video>
            <hr style="border-top-width: 5px; background-color: black;">
         </td>
      </tr>
      <% end %>
   </tbody>
</table>
<br>
<script>
   $(document).ready(function() {
      $(".video-js").each(function(){
        var movie_id = $(this)[0].id
        var concat = "#"+movie_id.toString()
        videojs(concat);
      }); 
      $('.hidethis').hide();
   });
</script>

app/views/movies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @movie.name %>
</p>

<p>
  <strong>Url:</strong>
  <%= @movie.url %>
</p>

<p>
  <strong>User:</strong>
  <%= @movie.user %>
</p>

<p>
  <strong>Public:</strong>
  <%= @movie.public %>
</p>

<%= link_to 'Edit', edit_movie_path(@movie) %> |
<%= link_to 'Back', movies_path %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>